import type { DatabaseSchema } from './schema';

const ts = (d = new Date()) => d.toISOString();

const cargoT1 = JSON.stringify([
  {
    id: 1,
    name: '电子设备 XL-200',
    spec: '标准',
    weight: '2000',
    volume: '12',
    pkg: '木箱',
  },
]);

const cargoT2 = JSON.stringify([
  {
    id: 1,
    name: '服装百货',
    spec: '普货',
    weight: '500',
    volume: '8',
    pkg: '编织袋',
  },
]);

/** 与历史 Mock 对齐的关系型初始数据 */
export function createSeedDatabase(): DatabaseSchema {
  const t0 = ts();

  return {
    agents: [
      {
        id: 'AG-001',
        name: '谅山鸿运车队',
        level_label: 'A级',
        code: 'VN-LS-001',
        location: '越南 谅山',
        contact: '黎司机',
        phone: '13800138000',
        biz_type: '干线运输 (中越/越老)',
        status: '已审核',
        remark: '',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'AG-002',
        name: '海防捷通报关行',
        level_label: 'B级',
        code: 'VN-HP-012',
        location: '越南 海防',
        contact: '张主管',
        phone: '13900139000',
        biz_type: '口岸清关',
        status: '已审核',
        remark: '',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'AG-003',
        name: '万象通跨境物流',
        level_label: 'A级',
        code: 'LA-VT-005',
        location: '老挝 万象',
        contact: '宋先生',
        phone: '13700137000',
        biz_type: '干线运输 (中越/越老)',
        status: '已审核',
        remark: '',
        created_at: t0,
        updated_at: t0,
      },
    ],

    app_users: [
      {
        id: 'int-001',
        username: 'admin',
        password: '123456',
        role: 'admin',
        portal: 'internal',
        display_name: '系统管理员',
        department: '运营总部',
        agent_id: null,
        status: 'active',
        permissions: ['dashboard', 'customers', 'agents', 'projects', 'tenders', 'system'],
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'int-002',
        username: 'staff',
        password: '123456',
        role: 'staff',
        portal: 'internal',
        display_name: '张业务',
        department: '跨境业务部',
        agent_id: null,
        parent_id: 'int-001',
        status: 'active',
        permissions: ['dashboard', 'projects'],
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'ag-usr-001',
        username: 'agent',
        password: '123456',
        role: 'agent',
        portal: 'agent',
        display_name: '谅山鸿运车队',
        department: null,
        agent_id: 'AG-001',
        status: 'active',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'ag-usr-002',
        username: 'agent2',
        password: '123456',
        role: 'agent',
        portal: 'agent',
        display_name: '海防捷通报关行',
        department: null,
        agent_id: 'AG-002',
        status: 'active',
        created_at: t0,
        updated_at: t0,
      },
    ],

    customers: [
      {
        id: 'CUS-001',
        name: '越南玖能国际有限公司',
        type: '外企',
        contact: '阮文强',
        phone: '+84 912 345 678',
        wechat: 'jn_vn_ops',
        biz_type: '工程物流',
        inquiry_count: 12,
        status: 'active',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'CUS-002',
        name: '云南某能源贸易商',
        type: '私企',
        contact: '李经理',
        phone: '13800138000',
        wechat: 'yn_energy_li',
        biz_type: '跨境干线',
        inquiry_count: 5,
        status: 'active',
        created_at: t0,
        updated_at: t0,
      },
    ],

    tenders: [
      {
        id: 'TND-202604-001',
        title: '广州至河内 电子设备专线',
        origin: '中国 广州',
        destination: '越南 河内',
        route_label: '中国 广州 → 越南 河内',
        deadline_at: '2026-04-05T18:00:00.000Z',
        status: 'evaluating',
        cargo_summary: '电子设备 XL-200 (2000kg)',
        requirements: '含清关，需提供时效承诺。',
        biz_type: '跨境干线',
        cargo_json: cargoT1,
        invited_agent_ids: ['AG-001', 'AG-002', 'AG-003'],
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'TND-202604-002',
        title: '深圳至海防 普货拼车',
        origin: '中国 深圳',
        destination: '越南 海防',
        route_label: '中国 深圳 → 越南 海防',
        deadline_at: '2026-04-06T12:00:00.000Z',
        status: 'bidding',
        cargo_summary: '服装百货 (500kg)',
        requirements: '拼车发运，需上门提货。',
        biz_type: '干线拼车',
        cargo_json: cargoT2,
        /** 验收场景：仅鸿运车队受邀 → 捷通报关 (AG-002) 代理端不应见单 */
        invited_agent_ids: ['AG-001'],
        created_at: t0,
        updated_at: t0,
      },
    ],

    bids: [
      {
        id: 'b3',
        tender_id: 'TND-202604-001',
        agent_id: 'AG-003',
        price: 11800,
        currency: 'CNY',
        status: 'pending',
        remarks: '特价线路，不含保险',
        estimated_time: '4天',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'b1',
        tender_id: 'TND-202604-001',
        agent_id: 'AG-001',
        price: 12500,
        currency: 'CNY',
        status: 'pending',
        remarks: '包含清关，预计3天送达',
        estimated_time: '3天',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'b2',
        tender_id: 'TND-202604-001',
        agent_id: 'AG-002',
        price: 13200,
        currency: 'CNY',
        status: 'pending',
        remarks: '自有车队，时效保障',
        estimated_time: '5天',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'b4',
        tender_id: 'TND-202604-002',
        agent_id: 'AG-001',
        price: 3500,
        currency: 'CNY',
        status: 'pending',
        remarks: '明晚发车',
        estimated_time: '2天',
        created_at: t0,
        updated_at: t0,
      },
    ],

    projects: [
      // ── 执行中项目（ActiveProjects 用）
      {
        id: 'PRJ-2604-01',
        tender_id: null,
        source_tender_id: null,
        winning_bid_id: null,
        agent_id: null,
        awarded_agent_id: null,
        client_id: null,
        client_name: '越南玖能国际',
        name: '凭祥至北宁工业园设备专线',
        origin: '广西凭祥',
        destination: '越南北宁',
        route: '广西凭祥 → 越南北宁',
        cargo_type: '设备',
        progress: 60,
        status: 'executing',
        manager: '张三',
        amount_display: null,
        source: 'manual',
        source_potential_id: null,
        current_location: '越南北宁',
        weight: '18 吨',
        eta: '2026-04-07',
        priority_label: 'High',
        transport_type: null,
        rating: null,
        completed_date: null,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'PRJ-2604-02',
        tender_id: null,
        source_tender_id: null,
        winning_bid_id: null,
        agent_id: null,
        awarded_agent_id: null,
        client_id: null,
        client_name: '云南某能源',
        name: '老挝木炭过境海防港发运',
        origin: '老挝萨拉万',
        destination: '越南海防',
        route: '老挝萨拉万 → 越南海防',
        cargo_type: '木炭',
        progress: 20,
        status: 'executing',
        manager: '李四',
        amount_display: null,
        source: 'manual',
        source_potential_id: null,
        current_location: '老挝沙拉湾',
        weight: '60 吨',
        eta: '2026-04-10',
        priority_label: 'Normal',
        transport_type: null,
        rating: null,
        completed_date: null,
        created_at: t0,
        updated_at: t0,
      },
      // ── 项目跟踪（Projects.tsx 用）
      {
        id: 'PRJ-2026-001',
        tender_id: null,
        source_tender_id: null,
        winning_bid_id: null,
        agent_id: null,
        awarded_agent_id: null,
        client_id: null,
        client_name: '老挝矿业集团',
        name: '老挝沙拉湾-越南-中国河口',
        origin: '老挝沙拉湾',
        destination: '中国河口',
        route: '老挝沙拉湾 → 越南 → 中国河口',
        cargo_type: '矿产物料',
        progress: 65,
        status: 'executing',
        manager: '张三',
        amount_display: '¥85,000',
        source: 'manual',
        source_potential_id: null,
        current_location: '越南岘港',
        weight: '240 吨',
        eta: '2026-04-06',
        priority_label: 'High',
        transport_type: '多式联运',
        rating: null,
        completed_date: null,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'PRJ-2026-002',
        tender_id: null,
        source_tender_id: null,
        winning_bid_id: null,
        agent_id: null,
        awarded_agent_id: null,
        client_id: null,
        client_name: '三星越南(SEV)',
        name: '胡志明市-凭祥-南宁',
        origin: '越南胡志明',
        destination: '中国南宁',
        route: '越南胡志明 → 中国南宁',
        cargo_type: '电子配件',
        progress: 100,
        status: 'executing',
        manager: '李四',
        amount_display: '¥45,000',
        source: 'manual',
        source_potential_id: null,
        current_location: '中国南宁',
        weight: '12 吨',
        eta: '2026-04-03',
        priority_label: 'Normal',
        transport_type: '陆运',
        rating: null,
        completed_date: null,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'PRJ-2026-003',
        tender_id: null,
        source_tender_id: null,
        winning_bid_id: null,
        agent_id: null,
        awarded_agent_id: null,
        client_id: null,
        client_name: 'Shopee跨境',
        name: '河内-东兴-广州',
        origin: '越南河内',
        destination: '中国广州',
        route: '越南河内 → 中国广州',
        cargo_type: '农产品',
        progress: 85,
        status: 'executing',
        manager: '王五',
        amount_display: '¥32,000',
        source: 'manual',
        source_potential_id: null,
        current_location: '中国东兴',
        weight: '45 吨',
        eta: '2026-04-05',
        priority_label: 'Normal',
        transport_type: '陆运',
        rating: null,
        completed_date: null,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'PRJ-2026-004',
        tender_id: null,
        source_tender_id: null,
        winning_bid_id: null,
        agent_id: null,
        awarded_agent_id: null,
        client_id: null,
        client_name: '华为技术',
        name: '曼谷-老挝-昆明',
        origin: '泰国曼谷',
        destination: '中国昆明',
        route: '泰国曼谷 → 老挝 → 中国昆明',
        cargo_type: '机械设备',
        progress: 10,
        status: 'preparing',
        manager: '赵六',
        amount_display: '¥120,000',
        source: 'manual',
        source_potential_id: null,
        current_location: '泰国曼谷',
        weight: '8 吨',
        eta: '2026-04-10',
        priority_label: 'High',
        transport_type: '多式联运',
        rating: null,
        completed_date: null,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'PRJ-2026-005',
        tender_id: null,
        source_tender_id: null,
        winning_bid_id: null,
        agent_id: null,
        awarded_agent_id: null,
        client_id: null,
        client_name: '宜家家居(IKEA)',
        name: '金边-越南-深圳',
        origin: '柬埔寨金边',
        destination: '中国深圳',
        route: '柬埔寨金边 → 越南 → 中国深圳',
        cargo_type: '纺织品',
        progress: 40,
        status: 'executing',
        manager: '张三',
        amount_display: '¥68,000',
        source: 'manual',
        source_potential_id: null,
        current_location: '越南胡志明',
        weight: '30 吨',
        eta: '2026-04-08',
        priority_label: 'Normal',
        transport_type: '多式联运',
        rating: null,
        completed_date: null,
        created_at: t0,
        updated_at: t0,
      },
      // ── 历史完成项目（ProjectHistory.tsx 用）
      {
        id: 'PRJ-2512-88',
        tender_id: null,
        source_tender_id: null,
        winning_bid_id: null,
        agent_id: null,
        awarded_agent_id: null,
        client_id: null,
        client_name: '三星越南(SEV)',
        name: '河内工业区电子配件空运专线',
        origin: '越南河内',
        destination: '中国深圳',
        route: '越南河内 → 中国深圳',
        cargo_type: '电子配件',
        progress: 100,
        status: 'completed',
        manager: '张三',
        amount_display: '¥45,000',
        source: 'manual',
        source_potential_id: null,
        current_location: null,
        weight: null,
        eta: null,
        priority_label: null,
        transport_type: '空运',
        rating: 5,
        completed_date: '2025-12-20',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'PRJ-2601-05',
        tender_id: null,
        source_tender_id: null,
        winning_bid_id: null,
        agent_id: null,
        awarded_agent_id: null,
        client_id: null,
        client_name: '宜家家居(IKEA)',
        name: '胡志明市家具海运出口项目',
        origin: '越南胡志明',
        destination: '中国上海',
        route: '越南胡志明 → 中国上海',
        cargo_type: '家具',
        progress: 100,
        status: 'completed',
        manager: '李四',
        amount_display: '¥128,000',
        source: 'manual',
        source_potential_id: null,
        current_location: null,
        weight: null,
        eta: null,
        priority_label: null,
        transport_type: '海运',
        rating: 4,
        completed_date: '2026-01-15',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'PRJ-2602-12',
        tender_id: null,
        source_tender_id: null,
        winning_bid_id: null,
        agent_id: null,
        awarded_agent_id: null,
        client_id: null,
        client_name: 'Shopee跨境',
        name: '中越跨境电商小包陆运',
        origin: '中国南宁',
        destination: '越南河内',
        route: '中国南宁 → 越南河内',
        cargo_type: '电商小包',
        progress: 100,
        status: 'completed',
        manager: '王五',
        amount_display: '¥86,500',
        source: 'manual',
        source_potential_id: null,
        current_location: null,
        weight: null,
        eta: null,
        priority_label: null,
        transport_type: '陆运',
        rating: 5,
        completed_date: '2026-02-28',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'PRJ-2603-01',
        tender_id: null,
        source_tender_id: null,
        winning_bid_id: null,
        agent_id: null,
        awarded_agent_id: null,
        client_id: null,
        client_name: '老挝矿业集团',
        name: '老挝矿产过境越南出口',
        origin: '老挝甘蒙',
        destination: '越南海防',
        route: '老挝甘蒙 → 越南海防',
        cargo_type: '矿产',
        progress: 100,
        status: 'completed',
        manager: '赵六',
        amount_display: '¥210,000',
        source: 'manual',
        source_potential_id: null,
        current_location: null,
        weight: null,
        eta: null,
        priority_label: null,
        transport_type: '多式联运',
        rating: 4,
        completed_date: '2026-03-10',
        created_at: t0,
        updated_at: t0,
      },
    ],

    potential_projects: [
      {
        id: 'P001',
        name: '老挝萨拉万木炭过境运输',
        client: '云南某能源贸易商',
        type: '跨境干线运输',
        amount: '¥ 150,000',
        status: '报价中',
        last_update: '2026-04-03',
        expected_date: '2026-04-15',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'P002',
        name: '越南农产品检测实验室合作',
        client: '胡志明市生物检疫局',
        type: '工程与设备采购',
        amount: '₫ 500,000,000',
        status: '初步沟通中',
        last_update: '2026-04-01',
        expected_date: '2026-05-10',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'P003',
        name: '北宁工业园厂房建设物资',
        client: '越南玖能国际有限公司',
        type: '工程物流配套',
        amount: '$ 45,000',
        status: '谈判中',
        last_update: '2026-04-04',
        expected_date: '2026-04-20',
        created_at: t0,
        updated_at: t0,
      },
    ],

    agent_applications: [
      {
        id: 'REQ-091',
        name: '前江生鲜检测中心',
        biz_type: '榴莲/菠萝蜜实验室检测与清关辅导',
        apply_date: '2026-04-03',
        contact: '武主管',
        phone: '0398765432',
        location: '越南 前江省',
        status: 'pending',
        login_account: 'qianjiang@test.com',
        reg_password: '123456',
        credit_code: '91440300MA5EXAMPLE1',
        doc_names: JSON.stringify(['营业执照副本', '道路运输经营许可证']),
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'REQ-092',
        name: '云南泰达冷链',
        biz_type: '中越冷链干线运输',
        apply_date: '2026-04-04',
        contact: '赵总',
        phone: '13988887777',
        location: '中国 云南',
        status: 'pending',
        login_account: 'taida@test.com',
        reg_password: '123456',
        credit_code: '91530100MA6EXAMPLE2',
        doc_names: JSON.stringify(['营业执照副本', '企业资质证明']),
        created_at: t0,
        updated_at: t0,
      },
    ],

    contracts: [
      {
        id: 'CTR-2604-A1',
        contract_type: 'award',
        tender_id: 'TND-202604-001',
        bid_id: 'b1',
        project_id: 'PRJ-2026-004',
        agent_id: 'AG-001',
        parent_contract_id: null,
        status: 'agent_signed',
        tender_snapshot: JSON.stringify({
          id: 'TND-202604-001',
          title: '广州至河内 电子设备专线',
          route_label: '中国 广州 → 越南 河内'
        }),
        bid_snapshot: JSON.stringify({
          id: 'b1',
          currency: 'CNY',
          price: 12500,
        }),
        agent_snapshot: JSON.stringify({
          id: 'AG-001',
          name: '谅山鸿运车队',
        }),
        platform_signee: null,
        agent_signee: '张海',
        agent_signed_at: t0,
        platform_confirmed_at: null,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'CTR-2604-E1',
        contract_type: 'execution',
        tender_id: 'TND-202604-001',
        bid_id: 'b1',
        project_id: 'PRJ-2026-004',
        agent_id: 'AG-001',
        parent_contract_id: 'CTR-2604-A1',
        status: 'pending_platform_confirm',
        tender_snapshot: JSON.stringify({
          id: 'TND-202604-001',
          title: '广州至河内 电子设备专线',
          route_label: '中国 广州 → 越南 河内'
        }),
        bid_snapshot: JSON.stringify({
          id: 'b1',
          currency: 'CNY',
          price: 12500,
        }),
        agent_snapshot: JSON.stringify({
          id: 'AG-001',
          name: '谅山鸿运车队',
        }),
        platform_signee: null,
        agent_signee: '张海',
        agent_signed_at: t0,
        platform_confirmed_at: null,
        created_at: t0,
        updated_at: t0,
      }
    ],

    project_alerts: [
      {
        id: 'ALT-001',
        type: 'delay',
        title: '运输延误 - R-102',
        desc: '由于凭祥口岸拥堵，预计延误4小时',
        time: '10分钟前',
        severity: 'high',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'ALT-002',
        type: 'customs',
        title: '清关异常 - C-505',
        desc: '越南海防港清关资料缺失，需补充原产地证明',
        time: '1小时前',
        severity: 'critical',
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'ALT-003',
        type: 'temp',
        title: '温度预警 - T-88',
        desc: '冷链车 VN-092 实时温度偏高 (当前: 4.2°C, 阈值: 4.0°C)',
        time: '2小时前',
        severity: 'medium',
        created_at: t0,
        updated_at: t0,
      },
    ],

    files: [],

    // ── 免费文件模板（公开下载）──────────────────────────────────────────
    free_templates: [
      // 出口文件
      {
        id: 'tmpl-exp-001',
        name: '商业发票模板（出口）',
        description: '标准出口商业发票格式，适用于越南、中国、老挝进出口贸易',
        category: 'export',
        bucket: 'templates',
        path: 'export/commercial-invoice-template.docx',
        original_name: '商业发票模板.docx',
        mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        size_bytes: 25600,
        storage_url: null,
        is_active: true,
        display_order: 1,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'tmpl-exp-002',
        name: '装箱单模板（出口）',
        description: '出口货物装箱单标准格式，包含件数、毛重、净重、体积信息',
        category: 'export',
        bucket: 'templates',
        path: 'export/packing-list-template.xlsx',
        original_name: '装箱单模板.xlsx',
        mime_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        size_bytes: 18400,
        storage_url: null,
        is_active: true,
        display_order: 2,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'tmpl-exp-003',
        name: '中华人民共和国出口货物报关单',
        description: '海关标准出口报关单格式，需按海关要求如实填写',
        category: 'export',
        bucket: 'templates',
        path: 'export/customs-declaration-export.pdf',
        original_name: '出口货物报关单.pdf',
        mime_type: 'application/pdf',
        size_bytes: 128000,
        storage_url: null,
        is_active: true,
        display_order: 3,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'tmpl-exp-004',
        name: '原产地证申请表（FORM E/CO）',
        description: '中国-东盟FORM E原产地证及一般原产地证CO申请表',
        category: 'export',
        bucket: 'templates',
        path: 'export/certificate-of-origin-application.pdf',
        original_name: '原产地证申请表.pdf',
        mime_type: 'application/pdf',
        size_bytes: 96500,
        storage_url: null,
        is_active: true,
        display_order: 4,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'tmpl-exp-005',
        name: '中英文销售合同模板',
        description: '进出口贸易中英文销售合同标准模板，含商品描述、价格条款、运输方式等',
        category: 'export',
        bucket: 'templates',
        path: 'export/sales-contract-template.docx',
        original_name: '中英文销售合同.docx',
        mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        size_bytes: 34500,
        storage_url: null,
        is_active: true,
        display_order: 5,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'tmpl-exp-006',
        name: '海运提单/空运单模板',
        description: '海运提单（B/L）及空运单（AWB）标准格式说明与填写指南',
        category: 'export',
        bucket: 'templates',
        path: 'export/bill-of-lading-guide.pdf',
        original_name: '提单填写指南.pdf',
        mime_type: 'application/pdf',
        size_bytes: 156000,
        storage_url: null,
        is_active: true,
        display_order: 6,
        created_at: t0,
        updated_at: t0,
      },
      // 进口文件
      {
        id: 'tmpl-imp-001',
        name: '商业发票模板（进口）',
        description: '进口商业发票格式要求，包含发票号、商品描述、成交价格等',
        category: 'import',
        bucket: 'templates',
        path: 'import/import-commercial-invoice.pdf',
        original_name: '进口商业发票格式.pdf',
        mime_type: 'application/pdf',
        size_bytes: 22800,
        storage_url: null,
        is_active: true,
        display_order: 1,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'tmpl-imp-002',
        name: '进口货物装箱单',
        description: '进口货物装箱单格式，需与发票信息一致',
        category: 'import',
        bucket: 'templates',
        path: 'import/import-packing-list.pdf',
        original_name: '进口装箱单格式.pdf',
        mime_type: 'application/pdf',
        size_bytes: 19200,
        storage_url: null,
        is_active: true,
        display_order: 2,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'tmpl-imp-003',
        name: '提单/运单正本',
        description: '海运提单正本或空运运单，是进口清关必备单据',
        category: 'import',
        bucket: 'templates',
        path: 'import/bill-of-lading-import.pdf',
        original_name: '进口提单说明.pdf',
        mime_type: 'application/pdf',
        size_bytes: 134000,
        storage_url: null,
        is_active: true,
        display_order: 3,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'tmpl-imp-004',
        name: '自动进口许可证申请表',
        description: '部分商品进口需办理自动进口许可证，此表为许可证申请表模板',
        category: 'import',
        bucket: 'templates',
        path: 'import/import-license-application.pdf',
        original_name: '自动进口许可证申请表.pdf',
        mime_type: 'application/pdf',
        size_bytes: 87500,
        storage_url: null,
        is_active: true,
        display_order: 4,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'tmpl-imp-005',
        name: 'CIQ检验检疫申请单',
        description: '中国海关出入境货物检验检疫申请单模板',
        category: 'import',
        bucket: 'templates',
        path: 'import/ciq-inspection-application.pdf',
        original_name: 'CIQ检验检疫申请单.pdf',
        mime_type: 'application/pdf',
        size_bytes: 112000,
        storage_url: null,
        is_active: true,
        display_order: 5,
        created_at: t0,
        updated_at: t0,
      },
      {
        id: 'tmpl-imp-006',
        name: '进口货物海关价格审定表',
        description: '海关审价时需提交的价格申报材料，包含成交价格调整项目说明',
        category: 'import',
        bucket: 'templates',
        path: 'import/customs-value-declaration.pdf',
        original_name: '海关价格审定表.pdf',
        mime_type: 'application/pdf',
        size_bytes: 78000,
        storage_url: null,
        is_active: true,
        display_order: 6,
        created_at: t0,
        updated_at: t0,
      },
    ],
  };
}
